name: altin_takip
description: "Altın Cüzdan - Altın takip uygulaması"
publish_to: 'none' 
version: 1.0.0+8

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.0
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  url_launcher: ^6.3.1
  flutter_riverpod: ^3.1.0
  gap: ^3.0.1
  shimmer: ^3.0.0
  dio: ^5.9.0
  fpdart: ^1.2.0
  flutter_animate: ^4.5.2
  get_it: ^9.2.0
  google_fonts: ^7.0.2
  equatable: ^2.0.8
  sticky_headers: ^0.3.0+2
  fl_chart: ^1.1.1
  flutter_svg: ^2.0.10+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1


flutter:

  uses-material-design: true

  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo.png"
